### ISSUE TITLE
How to dissable auto sort

### ISSUE THREAD

**Issue by Traineratwot** [valentin-morice/filament-json-column#6]
Hello a have a json like this 
```json
{
  "foo":1,
  "Bar":2
}
```
I need save this in this order BUT i see in database

```json
{
   "Bar": 2,
   "foo": 1
}
```

Please add setting to disable auto sort like that

```php
FilamentJsonColumn::make('data')->disableAutoSort()
```

**Comment by Traineratwot** [comment]
I am so sorry,  This problem turned out to be because of the database and not because of your component

**Comment by valentin-morice** [comment]
Thanks for the feedback, glad the issue resolved itself!
